### ISSUE TITLE
Estatísticas por  país, estado, municipio e região. 

### ISSUE THREAD

**Issue by cadu-leite** [barbaralluz/TG#13]
Contabiliar arvores no total e por status (condição), espécie ... 
1. Preparar uma base de teste . 
2. template com mapa e gráficos dessa pesquisa.

**Comment by cadu-leite** [comment]
Como sabemos de problemas para adiquirir polígonos de bairros por exemplo, 
podemos usar o campo CEP Para agrupar árvores em uma sub região da cidade.

**Comment by barbaralluz** [comment]
Iniciada criação de gráficos - estado e municipios

**Comment by barbaralluz** [comment]
Criados gráficos de acordo com condição, necessidade de manutenção, presença de rede elétrica, condição das raízes, estados e municipios;
Relacionada as issues  #19 e #18.

**Comment by cadu-leite** [comment]
Barbara, na mensagem de commit use `#num_issue`
ex.:

```
git commit -m "closed #9  - cria graficos ...  bla bla bla ..."
```

No lugar do closed pode ser usado ainda `fixed`, `closes`, `fixes`.
Dá uma olhada aqui em [1]

[1] -  https://github.com/blog/1386-closing-issues-via-commit-messages
