### ISSUE TITLE
Adicionar a documentação  - A problemática do endereço no brasil ...

### ISSUE THREAD

**Issue by cadu-leite** [barbaralluz/TG#15]
- Formato do endereço, se tem ou não um padrão e qual é  - Porque isso é importante. 
- A imortancia do endereço para a aplicação 
- A importancia da indentificação da árvoere. Maior qtd de dados possível. 
- Usabilidade - o problema de obter dados "crowd source"
-  e toda a problemática de uma app web.

**Comment by barbaralluz** [comment]
Adicionadas dificuldades encontradas ao desenvolver projeto.
