### ISSUE TITLE
Exemplo de issue referenciado outra issues e commits 

### ISSUE THREAD

**Issue by cadu-leite** [barbaralluz/TG#2]
Então uma issue pode referenciar a issue 1 -> #1 

e o commit de88ead

**Comment by cadu-leite** [comment]
Uma issue pode ser fechada na linha de comando da seguinte maneira
Ex.: 

```
git commit -m "close #34 - arruma bug do layout ad home"
```

ou seja 

  `close`ou  `fix`\+ `#<numero_da_issues>`

**Comment by cadu-leite** [comment]
E ainda posso referenciar pessoas 
cadu = @cadu-leite
ou barbara = @barbaralluz

**Comment by barbaralluz** [comment]
Issue criada como exemplo.
