### ISSUE TITLE
LIstas de arvores

### ISSUE THREAD

**Issue by cadu-leite** [barbaralluz/TG#9]
Colocar menos informação, possibilitando o usuário ver uma maior numero de linhas na tela. 
Sigestao de campso a serem mostrados na listagem:
- endereço completo (talvez sem os labels ex.: rua, numero e etc - o BootStrapTwitter tem uma formação de endereço padão.
- TALVEZ colocar um thumbnail, mas com certeza diminuir a foto ou retirá-la.

**Comment by barbaralluz** [comment]
Lista de árvores arrumada (busca e minhas árvores) - somente mostra endereço e espécie.

**Comment by cadu-leite** [comment]
mas cade o commit ?

**Comment by barbaralluz** [comment]
Desculpem, alterado no Commit c0b4ece
